package com.example.micro_finance.ui.fragment

import android.content.Context
import android.content.Intent
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.micro_finance.GramaKhataApplication
import com.example.micro_finance.R
import com.example.micro_finance.data.model.TransactionType
import com.example.micro_finance.databinding.FragmentDailyReportBinding
import com.example.micro_finance.ui.adapter.TransactionAdapter
import com.example.micro_finance.ui.viewmodel.GramaKhataViewModel
import com.example.micro_finance.ui.viewmodel.GramaKhataViewModelFactory
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class DailyReportFragment : Fragment() {

    private var _binding: FragmentDailyReportBinding? = null
    private val binding get() = _binding!!

    private val viewModel: GramaKhataViewModel by viewModels {
        GramaKhataViewModelFactory((requireActivity().application as GramaKhataApplication).repository)
    }

    private lateinit var adapter: TransactionAdapter

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentDailyReportBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        setupRecyclerView()
        observeViewModel()
    }

    private fun setupRecyclerView() {
        adapter = TransactionAdapter()
        binding.rvTodayTransactions.layoutManager = LinearLayoutManager(requireContext())
        binding.rvTodayTransactions.adapter = adapter
    }

    private fun observeViewModel() {
        viewModel.getTodayTransactions().observe(viewLifecycleOwner) { transactions ->
            adapter.submitList(transactions)
            
            val totalCollection = transactions.filter { it.type == TransactionType.TAKE }.sumOf { it.amount }
            binding.tvTotalCollection.text = getString(R.string.total_collection, totalCollection.toString())

            binding.btnShareReport.setOnClickListener {
                shareReport(totalCollection, transactions.size)
            }
        }
    }

    private fun shareReport(total: Double, count: Int) {
        val date = SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date())
        val sharedPref = requireActivity().getSharedPreferences("GramaKhataPrefs", Context.MODE_PRIVATE)
        val shopName = sharedPref.getString(getString(R.string.shop_name_pref_key), "Grama-Khata")
        
        val report = """
            *Daily Collection Report*
            Shop: $shopName
            Date: $date
            --------------------------
            Total Transactions: $count
            Total Collection: Rs. $total
            --------------------------
            Generated by Grama-Khata App
        """.trimIndent()

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_TEXT, report)
        }
        startActivity(Intent.createChooser(intent, "Share Report"))
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }
}
